"""empty message

Revision ID: 7866bedecd81
Revises: 
Create Date: 2024-11-17 19:17:50.999438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7866bedecd81'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('anon_id', sa.String(length=255), nullable=True),
    sa.Column('origin_link', sa.String(length=2048), nullable=False),
    sa.Column('short_link', sa.String(length=15), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('clicks', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_links_anon_id'), ['anon_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_links_short_link'), ['short_link'], unique=True)
        batch_op.create_index(batch_op.f('ix_links_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_links_user_id'))
        batch_op.drop_index(batch_op.f('ix_links_short_link'))
        batch_op.drop_index(batch_op.f('ix_links_anon_id'))

    op.drop_table('links')
    op.drop_table('users')
    # ### end Alembic commands ###
